### ISSUE TITLE
mask  folder

### ISSUE THREAD

**Issue by angellee0607** [opensuh/DocumentBinarization#6]
DIBCO does not have a mask folder. Should this folder be filled with the original image folder?
Is the mask made from the original image?

**Comment by Jihunn-Kim** [comment]
Sorry, it's a bit complicated as image path is hardcoded.

1. Download DIBCO image and maks(=ground truth) from https://vc.ee.duth.gr/dibco2019/
Please refer to the 4. Experimental Results of paper to find the image of the appropriate year.

2. Edit "Common/make_ground_truth_dibco.py" - image_dir, mask_dir (original image from website) and image_save_dir, mask_save_dir (patched image will be saved here).

3. Run "Common/make_ground_truth_dibco.py" (I can't remember exactly, but you need about 2 ~ 3 GB space for patched image)

4. Edit "DIBCO/train_step_all1.py" and run it - image_train_dir, mask_train_dir (folder which has patched image) and image_test_dir, mask_test_dir (original image from website)

**Comment by angellee0607** [comment]
> Sorry, it's a bit complicated as image path is hardcoded.
> 
> 1. Download DIBCO image and maks(=ground truth) from https://vc.ee.duth.gr/dibco2019/
>    Please refer to the 4. Experimental Results of paper to find the image of the appropriate year.
> 2. Edit "Common/make_ground_truth_dibco.py" - image_dir, mask_dir (original image from website) and image_save_dir, mask_save_dir (patched image will be saved here).
> 3. Run "Common/make_ground_truth_dibco.py" (I can't remember exactly, but you need about 2 ~ 3 GB space for patched image)
> 4. Edit "DIBCO/train_step_all1.py" and run it - image_train_dir, mask_train_dir (folder which has patched image) and image_test_dir, mask_test_dir (original image from website)

thank you very much!

**Comment by aabioumaima** [comment]
hi guys, could you help me solve this problem? 

after the training for step1 and step2, I get this error while i'm runing 'train_step2_resize.py ':




train len: 3
libpng warning: iCCP: known incorrect sRGB profile
Traceback (most recent call last):
  File "./DIBCO/train_step2_resize.py", line 284, in <module>
    unet_train(opt.epochs, opt.gpu, opt.base_model_name, opt.encoder_weights, opt.generator_lr, opt.discriminator_lr, opt.lambda_bce,
  File "./DIBCO/train_step2_resize.py", line 114, in unet_train
    for idx, (images, masks) in enumerate(train_loader):
  File "/home/oumaimaaabi/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 530, in __next__
    data = self._next_data()
  File "/home/oumaimaaabi/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 570, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/oumaimaaabi/.local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    return self.collate_fn(data)
  File "/home/oumaimaaabi/.local/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 172, in default_collate
    return [default_collate(samples) for samples in transposed]  # Backwards compatibility.
  File "/home/oumaimaaabi/.local/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 172, in <listcomp>
    return [default_collate(samples) for samples in transposed]  # Backwards compatibility.
  File "/home/oumaimaaabi/.local/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 138, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: stack expects each tensor to be equal size, but got [3, 423, 786] at entry 0 and [3, 467, 1742] at entry 1

**Comment by rmast** [comment]
Your focus should be on this shape-related issue:

> RuntimeError: stack expects each tensor to be equal size, but got [3, 423, 786] at entry 0 and [3, 467, 1742] at entry 1
